public enum Tiles{
	HERO, TRADER,
	WALL, CORRIDOR, ENTRANCE, EXIT, BODY, CONNECTOR, EDGE, CHEST,
	EARTH, FOREST, WATER, SAND, TRAIL, CAVE,
	POST, PIER, FENCE, STATUE1, STATUE2,
	PEN, PIG, COW, HORSE, FARMER, 
	GOBLIN, GHOST, SPIDER, TROLL, DEMON
	};